// var myNum = 5;
// var num = 5.3444444;
// console.log(typeof num);
// var value = num.toFixed(3);
// console.log(typeof value);
// console.log(typeof parseFloat(value));
var x = "";
x = !x;
console.log(!!x);
x = x++;
console.log(x);
x = ++x;
console.log(x);
